name: manage-azure-policy-acd40cca
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Apply_diagnostic_settings_for_Azure_App_Service_Plans_-_Log_Analytics_webServerFarm-diagnostic-settings-policyDef/**'
#      - 'policies/subscaudit_eb49cdf1-f45f-4215-a78a-f5d9b15973ae/**'
#      - .github/workflows/manage-azure-policy-acd40cca.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_acd40cca}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Apply_diagnostic_settings_for_Azure_App_Service_Plans_-_Log_Analytics_webServerFarm-diagnostic-settings-policyDef/**
          policies/subscaudit_eb49cdf1-f45f-4215-a78a-f5d9b15973ae/**
