name: manage-azure-policy-82ff50aa
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/enable_secure_data_transfer_0287e6dc-7231-49b6-8acc-a2f997b33199/**'
#      - 'policies/public_access_disable_sa_0287e6dc-7231-49b6-8acc-a2f997b33ca7/**'
#      - .github/workflows/manage-azure-policy-82ff50aa.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_82ff50aa}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/enable_secure_data_transfer_0287e6dc-7231-49b6-8acc-a2f997b33199/**
          policies/public_access_disable_sa_0287e6dc-7231-49b6-8acc-a2f997b33ca7/**
